development:
  adapter: postgresql
  encoding: unicode
  database: tutorial_development
  pool: 5
  username: pooya
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tutorial_test
  pool: 5
  username: pooya
  password: